name: AWS CI

on:
  workflow_call:
    inputs:
      cloud-platform:
        required: true
        type: string
      deregister:
        required: true
        type: boolean
        default: true

    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true

jobs:
  create-instances:
    name: Create instance from image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download image artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.cloud-platform }}-artifacts.json

    - name: Setup jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Extract image ID's and regions
      run: |
        redis_stack_x86_image_id=$(cat ${{ inputs.cloud-platform }}-artifacts.json | jq -r '.builds[] | select(.name == "redis-stack-x86").artifact_id | split(":") | .[1]' )
        echo "redis_stack_x86_image_id='${redis_stack_x86_image_id}'" >> $GITHUB_ENV
        redis_stack_x86_region=$(cat ${{ inputs.cloud-platform }}-artifacts.json | jq -r '.builds[] | select(.name == "redis-stack-x86").artifact_id | split(":") | .[0]' )
        echo "redis_stack_x86_region='${redis_stack_x86_region}'" >> $GITHUB_ENV
    #     redis-stack-arm-image-id=$(jq -r '.builds[] | select(.name == "redis-stack-arm") | ${{ inputs.cloud-platform }}-artifacts.json)
    #     echo "redis-stack-arm-image-id=${redis-stack-arm-image-id}" >> $GITHUB_ENV

    #create ssh key for ec2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.redis_stack_x86_region }} #until we support multi regions

    - name: check-key-pair
      run: |
        aws ec2 describe-key-pairs --key-name redis-stack-packer-ci --query 'KeyPairs[*].KeyName' --output text
      id: check-key-pair
      continue-on-error: true

    - name: Create key pair if it does not exist
      if: steps.check-key-pair.outcome != 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        aws ec2 create-key-pair --key-name redis-stack-packer-ci --query 'KeyMaterial' --output text > redis-stack-packer-ci.pem
        gh secrets SSH_PRIVATE_KEY > redis-stack-packer-ci.pem

    - name: Print message if key pair already exists
      if: steps.check-key-pair.outcome == 'success'
      run: echo "Key pair 'redis-stack-packer-ci' already exists, skipping creation."

    - name: Create an EC2 instance - x86
      run: |
        echo ${{ env.redis_stack_x86_image_id }}
        aws ec2 run-instances --image-id ${{ env.redis_stack_x86_image_id }} --key-name redis-stack-packer-ci --region ${{ env.redis_stack_x86_region }}

    - name: SSH into the EC2 instance - x86
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ steps.create_ec2_instance.outputs.public_ip }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Python and pip
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          
          # Install pipenv
          pip3 install pipenv
          
          # Clone redis-stack/redis-stack repo
          git clone https://github.com/redis-stack/redis-stack.git
          
          # Change directory
          cd redis-stack
          
          # Install the dependencies
          pipenv install --dev
          
          # Run pytest command
          pipenv run pytest -m 'jammy and not arm'

    # - name: Create an EC2 instance - arm
    #   env:
    #     redis-stack-arm-image-id: $(jq -r '.builds[] | select(.name == "redis-stack-arm") | ${{ inputs.cloud-platform }}-artifacts.json)
    #   run: |
  #      aws ec2 run-instances --image-id ${{ env.redis-stack-arm-image-id }} --key-name redis-stack-packer-ci

    # - name: SSH into the EC2 instance and test - arm
    #   uses: aws-actions/ssh-action@main
    #   with:
    #     host: ${{ steps.create_ec2_instance.outputs.public_ip }}
    #     username: ubuntu
    #     key: redis-stack-packer-ci.pem
    #     commands: |
    #       # Install Python and pip
    #       sudo apt-get update
    #       sudo apt-get install -y python3 python3-pip
          
    #       # Install pipenv
    #       pip3 install pipenv
          
    #       # Clone redis-stack/redis-stack repo
    #       git clone https://github.com/redis-stack/redis-stack.git
          
    #       # Change directory
    #       cd redis-stack
          
    #       # Install the dependencies
    #       pipenv install --dev
          
    #       # Run pytest command
    #       pipenv run pytest -m "jammy"

    # - name: Deregister AMI 
    #   if: ${{ inputs.deregister == true }}
    #   run: |
    #     aws ec2 deregister-image --image-id="ami-055ff4aae33b69ace" --region="us-east-1"
      